spring:
  kafka:
    bootstrap-servers: "exchange-1.int.herron.se:9092"

kafka:
  topic:
    herron-order-data:
      nr-of-partitions: 1

subscription-config:
  uri: wss://ws.bitstamp.net
  channels:
    - live_orders_btceur
    - live_orders_btcusd
    - live_orders_xrpeur
    - live_orders_xrpusd
