spring:
  kafka:
    bootstrap-servers: "localhost:9092"

kafka:
  topic:
    order-data:
      nr-of-partitions: 1

subscription-config:
  uri: wss://ws.bitstamp.net
  channels:
    - live_orders_btcusd