spring:
  kafka:
    bootstrap-servers: "localhost:9092"

subscription-config:
  uri: wss://ws.bitstamp.net
  subscription-details:
    - channel: live_orders_btceur
    - channel: live_orders_btcusd
    - channel: live_orders_xrpeur
    - channel: live_orders_btcusd
