spring:
  kafka:
    bootstrap-servers: "localhost:9092"

subscription-config:
  uri: wss://ws.bitstamp.net
  channels:
    - live_orders_btceur
    - live_orders_btcusd
    - live_orders_xrpeur
    - live_orders_btcusd
